### ISSUE TITLE
[SCSS not SASS] Correct path for SCSS import in Data Viz Addon Readme

### ISSUE THREAD

**Issue by JackReis** [carbon-design-system/carbon-addons-data-viz-react#102]
## Detailed description

The current Readme has a path with `sass` instead of `scss` for the directory from which the data viz component styles are going to be loaded.

Corrected import should be from 

`carbon-addons-data-viz-react/scss/index.scss`

**Comment by JackReis** [comment]
@tw15egan Hey! Not sure if this is a good format but - I found something I think is probably an easy update for my first contribution :-)

**Comment by tw15egan** [comment]
Would definitely welcome a fix for this! 😄
