### ISSUE TITLE
GaugeGraph does not change with props

### ISSUE THREAD

**Issue by theoshu** [carbon-design-system/carbon-addons-data-viz-react#106]
## Detailed description

Gauge graph circle does not change based on props

> Is this issue related to a specific component?

GaugeGraph

> What did you expect to happen? What happened instead? What would you like to see changed?

If I pass 50 to the value prop, the gauge should fill to 50%

> What browser are you working in?

GC, FF quantum

> What version of the Carbon Design System are you using?

carbon-addons-data-viz-react 1.20.3

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

This is for an internal dashboard, so not high priority

## Steps to reproduce the issue

See code sandbox: https://codesandbox.io/s/lx519nj139

## Additional information

<img width="218" alt="gaugegraph" src="https://user-images.githubusercontent.com/4643524/39927733-d63db522-54f8-11e8-992b-8a62c105d950.png">

## Add labels
bug

**Comment by ArkejGit** [comment]
According to the docs there's no property like _value_ within **Gauge Graph**. You should use _amount_ instead:

`amount={50}`

Your sandbox fixed code: https://codesandbox.io/s/k3y3x4ylo3
