### ISSUE TITLE
Bargraph bars on hover show X-axis and Y-axis data together 

### ISSUE THREAD

**Issue by brsebas** [carbon-design-system/carbon-addons-data-viz-react#108]
<!-- Feel free to remove sections that aren't relevant.

## Bargraph bars on hover show X-axis and Y-axis data together 

.

brian>>My requirement is to show just Y-axis data .How do i stop it from displaying X-axis data

## Detailed description

brian>>My requirement is to show just Y-axis data on hover over the bars in the Bargraph  .How do i stop it from displaying X-axis label . Currently there is no space between the X-axis and Y-axis data thus making it invalid to read for the end user . 

> Is this issue related to a specific component?
brian>>My issue is related to Bar graph componenet

> What did you expect to happen? What happened instead? What would you like to see changed?

brian>>My requirement is to show just Y-axis data on hover over the bars in the Bargraph

> What browser are you working in?
brian>>chrome

> What version of the Carbon Design System are you using?
brian>>1.20.3

## Steps to reproduce the issue

1. Hover over the bars 

## Additional information
![bar_hover_issue](https://user-images.githubusercontent.com/40016218/41080015-0e14ba28-6a42-11e8-8819-04191f78f6bb.jpg)

code
<BarGraph
                      data={ graphDataState }
                      width={ 1220 }
                      height={ 350 }
                      id="graph"
                      containerId="containerId"
                      xAxisLabel={ selectedIdTimeframe }
                      yAxisLabel={ selectedIdEntitlement }
                      emptyText="There is currently no data available"
                      color={['#00a68f', '#3b1a40']}

                       />

**Comment by tw15egan** [comment]
Closing due to lack of information. Please feel free to reopen following the issue tempalte
