### ISSUE TITLE
Gauge graph doesn't change color.

### ISSUE THREAD

**Issue by Luc-Olsthoorn** [carbon-design-system/carbon-addons-data-viz-react#118]
## Detailed description

I am using:
    "carbon-addons-data-viz-react":"1.21.0",
    "carbon-components": "^9.0.0",
    "carbon-icons": "latest",
     "carbon-components-react": "6.12.0"
The Guage graph works well, except it always has the same fill color. After I looked at the underlying code, I expected this to change out of the box(?), but it also doesn't work with user-defined values either ie.
[{ low: 0, high: 50, color: '#4B8400' },{ low: 50, high: 75, color: '#EFC100' },{ low: 75, high: 100, color: '#FF5050' }]

## Steps to reproduce the issue

```
import { connect } from 'react-redux'
import React from 'react';
import { GaugeGraph } from 'carbon-addons-data-viz-react';
const Main = ({ severity }) => {
  return (
    <div>
      <GaugeGraph  labelText = {"Severity"} valueText= {severity + " / 5" } amount={60} total={100}/>
    </div>
  )
}
```

## Additional information

<img width="258" alt="screen shot 2018-07-19 at 4 20 34 pm" src="https://user-images.githubusercontent.com/14364864/42967935-d165af52-8b6f-11e8-84f7-af5c962f2ea5.png">

I may be doing something completley dumb, but have spent quite a while trying to debug this! 
Thanks!

**Comment by williamgoodhew** [comment]
is there any update on this?

**Comment by tw15egan** [comment]
This library has been deprecated in favor of [Carbon Charts](https://github.com/carbon-design-syst…)
