### ISSUE TITLE
Module not found: Error: Can't resolve 'babel-runtime/core-js/object/get-prototype-of ... \BarGraph

### ISSUE THREAD

**Issue by bazquezero** [carbon-design-system/carbon-addons-data-viz-react#120]
## Detailed description

I'm having troubles every time I use `npm install` on my project after added this package, the webpack bundle won't be compiled, because one module seems to be missing, and all the components need it.

 I would like to know if is related to any missing dependencies, so I would like to be tokd 

Carbon Design System:

    "carbon-addons-cloud": "^2.2.0",
    "carbon-addons-cloud-react": "^1.3.2",
    "carbon-addons-data-viz-react": "^1.21.0",
    "carbon-components": "^9.9.1",
    "carbon-components-react": "^6.28.1",
    "carbon-icons": "^7.0.7",

## Steps to reproduce the issue

    $  webpack-dev-server --config-name client-dev --env.wds --progress --open

## Additional information

* Screenshots or code
![image](https://user-images.githubusercontent.com/38488822/45509684-7ce0a380-b755-11e8-9b4e-46ae0f5af1e2.png)

* Notes
Every time this happen, I enter the `node_modules/carbon-addons-data-viz-react` and use `npm install`

**Comment by tw15egan** [comment]
Hmm, `babel-preset-env` may need to be added to the project dependencies

**Comment by bazquezero** [comment]
In my project? I'm already using this babel packages:

dependencies:

     "@babel/polyfill": "^7.0.0",

devDependencies:

     "@babel/core": "^7.0.0",
     "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
     "@babel/preset-env": "^7.0.0",
     "@babel/preset-react": "^7.0.0",

and my webpack config for the js files is:

    {
        test: /\.jsx?$/,
        include: [path.resolve(__dirname, 'src')],
        exclude: /(node_modules)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env', '@babel/preset-react'],
            plugins: [require('@babel/plugin-proposal-object-rest-spread')]
          }
        }
     },

**Comment by tw15egan** [comment]
Seems like the error is coming because this plugin isn't installed: https://babeljs.io/docs/en/babel-plugin-transform-object-set-prototype-of-to-assign

Do you think this needs to be added to the main repo? Would accept any PR's that fix this issue back into the main repo 😄
