### ISSUE TITLE
Stop depending on Carbon packages?

### ISSUE THREAD

**Issue by s100** [carbon-design-system/carbon-addons-data-viz-react#146]
## Detailed description

> Is this issue related to a specific component?

No.

> What did you expect to happen? What happened instead? What would you like to see changed?

I am trying to use `carbon-addons-data-viz-react` in a Carbon 10 project. I was hoping that there would be a version of this package which supports Carbon 10, but looking at `package.json` we see (in part):

```json
{
  "dependencies": {
    "carbon-components": "^8.0.0",
    "carbon-components-react": "^5.0.0",
    "carbon-icons": "^6.1.0"
  },
  "devDependencies": {
    "carbon-components": "^8.0.0",
    "carbon-components-react": "^5.0.0",
    "carbon-icons": "^6.1.0"
  }
}
```

First of all we note the redundancy. A production dependency is implicitly also a development dependency, so the second block can be scrapped... maybe. However, read on...

Second we see that we depend on `carbon-components@^8.0.0` which is Carbon 8. Following the release of Carbon 10 this year, this is two major versions out of date and it would be great if there was a version of `carbon-addons-data-viz-react` which supported the new Carbon.

Thirdly, after a quick skim of the source code it looks as if these three packages are not actually used *anywhere* directly by this package. The only exception is [`.storybook/_container.scss`](https://github.com/carbon-design-system/carbon-addons-data-viz-react/blob/0006d2b607849bc86554440e5461b507e577848e/.storybook/_container.scss#L3):

```scss
@import '~carbon-components/scss/globals/scss/styles.scss';
```

This is a React Storybook SCSS file used only at development time.

So it could be that *no* version of Carbon is actually required for this package to work in production! If this is the case, we could scrap the production dependencies instead of the development dependencies, resulting in a version of `carbon-addons-data-viz-react` which is Carbon-agnostic. We could then consider removing the development dependencies on `carbon-components-react` and `carbon-icons` too, since they are unused.

> What version of the Carbon Design System are you using?

10.

## Steps to reproduce the issue

1. Try to use `carbon-addons-data-viz-react` in a Carbon 10 project.
2. Observe multiple clashing versions of `carbon-components-react` in your `node_modules`.

**Comment by asudoh** [comment]
Hi 👋 would you want to take a look at https://github.com/carbon-design-system/carbon-charts, where you can see recent activities?

**Comment by s100** [comment]
@asudoh `@carbon/charts` doesn't seem to be ready for production just yet. It's still at version 0, I've been unable to find documentation for any of its chart types, and it doesn't seem to be able to do elementary things like a scatter plot with lines joining the scattered points, which is what we need.

I've opened PR #147 which I think will fix the current issue (#146)... is this PR likely to be accepted in the near future? If not, we will look for an alternative charting component.

**Comment by asudoh** [comment]
CC @theiliad to see the stability of the codebase. Thanks!

**Comment by cknabe** [comment]
#147 is a good stop-gap for those of us who have a massive transformation to Carbon 10

If we simply remove the dependencies and then carbon 10 themes are applied, will the colors/fonts of this lib look horrible against carbon 10?

**Comment by theiliad** [comment]
> CC @theiliad to see the stability of the codebase. Thanks!

Hi. `@carbon/charts` has been refactored to function as a charting framework that's allowed us to expand to tons of different graph types within the past 2 months.

@s100 please reach out if you have any questions/feature requests.

The scatter line plot you've asked for above has been available since the early days of the library. We are working on adding more documentation and examples to the website.

https://carbon-design-system.github.io/carbon-charts/react/?path=/story/line--line-time-series
https://github.com/carbon-design-system/carbon-charts/blob/4a3727d13796030866e1416effdc48b274bdb401/packages/core/demo/demo-data/line.ts#L4-L126
