### ISSUE TITLE
GaugeGraph-Value text and labelText props always affect the first graph, when there are multiple graphs.

### ISSUE THREAD

**Issue by sandhya-r-reddy** [carbon-design-system/carbon-addons-data-viz-react#16]
![screen shot 2017-09-25 at 2 36 39 pm](https://user-images.githubusercontent.com/32277486/30827219-0397a1f2-a1ff-11e7-8ee6-e3321aee97b2.png)

When we try to render multiple graphs, only the value and label text of first graph are affected.

**Comment by elarue3824** [comment]
It says this bug was fixed, but it is still present.
<img width="1552" alt="screen shot 2019-01-23 at 10 07 29 am" src="https://user-images.githubusercontent.com/42156684/51619889-de303480-1ef6-11e9-93af-766cf9198633.png">

**Comment by hanymichael** [comment]
Having the same issue. Any fix please?
