### ISSUE TITLE
I don't see empty text component for 2 graphs when no data is present

### ISSUE THREAD

**Issue by amortiz** [carbon-design-system/carbon-addons-data-viz-react#25]
Oops, not using latest version :) disregard

**Comment by amortiz** [comment]
When i have 2 graph components, and both of them have no data, the empty text only shows up on the first graph.

I believe:
.select('.bx--line-graph-empty-text')
is selecting the 1st empty text for both graphs, maybe it needs to be more specific th match the selector within the graph component?

**Comment by tw15egan** [comment]
Yup, that's it. When I was creating these components, in my haste I forgot to realize there would usually be more than one graph per page. Will update each selector to require a unique id
