### ISSUE TITLE
Line graph shows an empty graph when only 1 data point is passed

### ISSUE THREAD

**Issue by amortiz** [carbon-design-system/carbon-addons-data-viz-react#32]
When the data is an array of One element only, we get an empty graph:

![image](https://user-images.githubusercontent.com/10033254/31443970-6793454a-ae60-11e7-8248-e60996d7259c.png)

I would expect to either see a single dot on the graph, or if that's not feasible, I would think showing the 'no data available' message would also be acceptable.

**Comment by tw15egan** [comment]
I can change the 'No Data Available` minimum threshold to 1 element (currently 0)
