### ISSUE TITLE
Default values for gauage component are always visible

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon-addons-data-viz-react#38]
@vidyakhadsareibm commented on [Fri Oct 13 2017](https://github.com/carbon-design-system/carbon-components-react/issues/281)

Default values for amount and total (75 out of 100GB) are always visible. There was a requirement to hide those values because we dont have valid data to be displayed right now.

<img width="1564" alt="screen shot 2017-10-12 at 3 55 42 pm" src="https://user-images.githubusercontent.com/32777878/31559898-1f8c6ab2-b007-11e7-9335-ed2042fc950d.png">

---

@tw15egan commented on [Fri Oct 13 2017](https://github.com/carbon-design-system/carbon-components-react/issues/281#issuecomment-336531746)

@vidyakhadsareibm, this issue deals with the `carbon-addons-data-viz-react` repo, so I'm going to move this issue over there.

**Comment by tw15egan** [comment]
Can you solve this by passing in empty strings for `labelText` and `valueText`?

**Comment by vidyakhadsareibm** [comment]
I tried but it still shows these default values.

**Comment by tw15egan** [comment]
Hm, what props are you passing in? I'm able to pass in empty strings and get no labels

![screen shot 2017-10-13 at 1 58 35 pm](https://user-images.githubusercontent.com/11928039/31561784-a2d79db2-b01e-11e7-8b65-b8721f112b01.png)

![screen shot 2017-10-13 at 1 58 29 pm](https://user-images.githubusercontent.com/11928039/31561791-a860a508-b01e-11e7-9bec-f27202e17344.png)

**Comment by vidyakhadsareibm** [comment]
You are right. I tried not passing 'labelText' property at all yesterday. I didnt really assign empty string. It was displaying default if I dont pass value. It is working with empty string. Thank you so much for your help.

**Comment by tw15egan** [comment]
Great! Glad I could help out 😃
