### ISSUE TITLE
Gauge Graph colors should be customizable 

### ISSUE THREAD

**Issue by joker23** [carbon-design-system/carbon-addons-data-viz-react#51]
## Detailed description

Currently the gauge colors in the gauge graph is hard coded to specific values. This issue also extends to the the gauge percentages, which, currently, is expected to only honor the first 2 entries.

> Is this issue related to a specific component?
GaugeGraph

> What did you expect to happen? What happened instead? What would you like to see changed?
Developers should be able to define their own gauge colors and their own percent thresholds (beyond only 2 thresholds).

**Comment by tw15egan** [comment]
What use-cases / format would you suggest for the gauge percentages / custom colors?

**Comment by joker23** [comment]
I would say an array of ranges formatted in such a way:
```
{
  hi: <upper bound>,
  lo: <lower bound>,
  color: <color for that range>
}
```

The array will be sorted by priority so the code to discern the color of the gauge line will iterate through the ranges in order and choose the first color that the percent is in the range.

**Comment by tw15egan** [comment]
@joker23 I created https://github.com/carbon-design-system/carbon-addons-data-viz-react/pull/52, would this resolve the issue?
