### ISSUE TITLE
webpack config

### ISSUE THREAD

**Issue by ryanomackey** [carbon-design-system/carbon-addons-data-viz-react#68]
Not really an issue, but I had to have webpack alias d3 to get everything to work properly:
```
module.exports = {
  ...other config stuff
  resolve: {
    alias: {
        d3: 'd3/build/d3.js'
    },
  },
};
```
Just wanted to jot this down somewhere.

**Comment by tw15egan** [comment]
Hmm that's odd. Should this be added to the projects `webpack.config`?

**Comment by ryanomackey** [comment]
Not if you're not having any trouble. Just might be a good addition to the docs. Specifically `webpack 3.10.0`.
