### ISSUE TITLE
Update to carbon-components-react@5.x?

### ISSUE THREAD

**Issue by chrisbygrave** [carbon-design-system/carbon-addons-data-viz-react#72]
Using `carbon-addons-data-viz-react` alongside the latest `carbon-components-react` causes unmet peer dependencies - one depends on react@15 and the other on react@16. Is there a plan to update this repo to the latest carbon components react?

**Comment by tw15egan** [comment]
Can update it now

**Comment by chrisbygrave** [comment]
Awesome - thanks for the quick action
