### ISSUE TITLE
DataTooltip missing styles

### ISSUE THREAD

**Issue by dcostantino** [carbon-design-system/carbon-addons-data-viz-react#76]
The DataTooltip styles seem to be missing:
![image](https://user-images.githubusercontent.com/22599308/36440819-a35c8334-163e-11e8-8d12-a710b337b5fa.png)

**Comment by tw15egan** [comment]
Are you importing the styles from the component?

**Comment by dcostantino** [comment]
No I was not importing, did not know I need to, was not documented.

**Comment by tw15egan** [comment]
Will add in documentation!
