### ISSUE TITLE
DataTooltip styling issues - text overflow & positioning

### ISSUE THREAD

**Issue by dcostantino** [carbon-design-system/carbon-addons-data-viz-react#77]
When a name is long it overruns the tooltip box:

![image](https://user-images.githubusercontent.com/22599308/36485895-419998c8-16eb-11e8-937e-a2d220357348.png)

**Comment by dcostantino** [comment]
Also right position does not seem to be working correctly:
Left looks correct: 
![image](https://user-images.githubusercontent.com/22599308/36492216-987c69ea-16fa-11e8-8e12-e0e486d88676.png)
But right does not:
![image](https://user-images.githubusercontent.com/22599308/36492253-bb4982a0-16fa-11e8-8bc1-b665d120d9bf.png)

**Comment by tw15egan** [comment]
You will need to move the tooltip to the left, if you are going to set the direction to the right. The tooltip itself has no positional awareness in terms of the entire DOM. 

The example you are posting does not seem to be following the guidelines found here: http://www.carbondesignsystem.com/data-vis/tooltip/usage

A single point data tooltip should look like this
![screen shot 2018-02-21 at 10 42 16 am](https://user-images.githubusercontent.com/11928039/36492904-e9c85964-16f3-11e8-8370-955b4d183c18.png)
