### ISSUE TITLE
DataTooltip styling: bug with scss

### ISSUE THREAD

**Issue by Kathleen-Francis** [carbon-design-system/carbon-addons-data-viz-react#88]
## Detailed description

When I use DataTooltip in my app, the styling is wrong. If I inspect the element, I can see that the styles of `bx--tooltip` and `bx--tooltip--shown` are being applied, but not the styles of `bx--data-tooltip` (which should be coming from scss file). 

Has `bx--data-tooltip` as a class:
<img width="443" alt="screen shot 2018-03-07 at 10 38 17 am" src="https://user-images.githubusercontent.com/35227304/37101507-c403e990-21f3-11e8-9c51-a7ee71912179.png">

But doesn't show any styles from it:
<img width="470" alt="screen shot 2018-03-07 at 10 38 25 am" src="https://user-images.githubusercontent.com/35227304/37101528-cde3667a-21f3-11e8-8c95-59d43643f7b0.png">

The styling works fine when working in Storybook, so I think it might be an issue with how the scss is handled in the build. I don't know much about scss but I did look into the build script and notice that the 'node-sass' package is imported but never used -- not sure if that might be related.

> Is this issue related to a specific component?

DataTooltip

> What did you expect to happen? What happened instead? What would you like to see changed?

Should look like this: 
<img width="116" alt="screen shot 2018-03-07 at 10 33 11 am" src="https://user-images.githubusercontent.com/35227304/37101216-012d5046-21f3-11e8-929f-6949d22dd773.png">

Instead looks like this:
<img width="179" alt="screen shot 2018-03-07 at 10 33 05 am" src="https://user-images.githubusercontent.com/35227304/37101227-070cd842-21f3-11e8-85d0-5e8ecff28e69.png">

> What browser are you working in?

Chrome, Firefox

**Comment by tw15egan** [comment]
Think I just need to reset some of the `bx--tooltip` styles, like padding, that are being added to the overall `data-tooltip` container. Will take a look

**Comment by tw15egan** [comment]
@Kathleen-Francis how are you importing the `data-tooltip` styles?

**Comment by Kathleen-Francis** [comment]
Currently, I'm not importing any styles. I tried importing the scss from the node_modules folder but it didn't make a difference.

**Comment by tw15egan** [comment]
The styles need to be imported from `PATH_TO_NODE_MODULES/carbon-addons-data-viz-react/sass/index`, otherwise no `data-tooltip` styles will be applied.

**Comment by Kathleen-Francis** [comment]
That didn't work for me. But I'm not using scss anywhere else in the project so maybe it's a configuration issue on my end?

**Comment by tw15egan** [comment]
Yes, that seems like the case, I would make sure the `scss` is being compiled and is showing up in your `css` file. You could try searching your `css` file for some of the specific `data-tooltip` classes

**Comment by shinytoyrobots** [comment]
Don't believe it is an actual bug, hopefully guidance above has helped.
